name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 217.114.1.63 >> ~/.ssh/known_hosts
      - name: Debug SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no root@217.114.1.63 "echo 'SSH работает!'"
      - name: Deploy to server
        run: |
          ssh root@217.114.1.63 << 'EOF'
            cd /root/osushenie_bot/SVVR_Osushenie_bot || exit
            git pull origin main || exit
            pkill -f 'python3 main.py'
            nohup python3 main.py &
          EOF
